# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ac616ede19da16ad2675e288127893032e925fb36802e8457d8b03282b58231340470e6e50d533059f1e2792879c6491703fa8ed5f8ea3a31dc540abdb1a3da

test:
  secret_key_base: 1b566bce8c26d182c4f91f83822cec0fab53361e8ee727e20de5ce0aec6136971d23bd0a2a0a0dd522d89f6e9ac37a83b5768fac1486f15b8de336ecb139a6b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
